### ISSUE TITLE
As the EOEPCA+ Application Quality Building Block, I want to know the GitHub location of example CDSE source code, so that I can do analysis on this code

### ISSUE THREAD

**Issue by JanssenBrm** [ESA-EarthCODE/EarthCODE#18]
Done Criteria:
Provide a GitHub reference 

This is so that the EOEPCA+ Application Quality Building Block can see some real code. 
They might consider 
Static code analysis
Performance analysis
Unit tests
etc

**Comment by jdries** [comment]
Related APEx/EOEPCA+ epic: https://github.com/EOEPCA/roadmap/issues/305

Very important to not get confused:
EOEPCA has modelled 'health' and 'quality' as two very distinct BB's, that are executed by separate organizations.
Unfortunately there is a mismatch with openEO and in fact EO in general.

**EO application health AND quality depend on INPUT DATA**

So the project writes 'high quality' python code, with 100% test coverage and 0 linting warnings.
The project sets up a local benchmark, showing good performance.

=> This has only a marginal effect on the 'quality' perceived by the end user.

What does affect the user?
- Data providers change data input format (like upcoming change to ZARR). Does the application break, or does it continue to work?
- Data providers make a reprocessing, resulting in small changes in input values => is the algorithm robust to these small changes, or does it suddenly break or give wrong output?
- There's a unexpected gap in the satellite observations, what happens?
- The algorithm has bad performance, because the input data is stored on a storage system that doesn't like the access pattern that was benchmarked by the implementor.


So conclusion: application health and quality are two closely related properties, that both require regular checking of how the algorithm behaves in the real-world operational environment, usually of a specific hosting platform.

**Comment by JanssenBrm** [comment]
As an example, you can use the WorldCereal case, available at https://github.com/WorldCereal/worldcereal-classification. This project features a Python implementation suitable for code quality checks. However, as noted by @jdries, the impact of these checks on the overall quality of the service from the user's perspective may be limited.  

To ensure a more robust quality assurance process, it would be beneficial to also incorporate end-to-end (e2e) and benchmark tests. These tests can verify that the output remains consistent with validated results while ensuring that the service performs efficiently. For instance, if a new version introduces a non-optimized section of code, unit tests may still pass, but the cost of running the service could unexpectedly increase. Benchmarks can help detect such issues early and maintain performance within acceptable limits.
